name: Flowise PR Review

on:
  issue_comment:
    types: [created]

jobs:
  review-pr:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'Arto review')
    runs-on: ubuntu-latest

    steps:
      - name: Send PR details to Flowise Agent
        run: |
          curl -X POST https://flowiseai-inv-u36837.vm.elestio.app/api/v1/prediction/e7cf97b0-fbd7-4975-87d0-832ae6853acc \
            -H "Content-Type: application/json" \
            -d "$(jq -n \
              --arg repo "${{ github.repository }}" \
              --arg pr_number "${{ github.event.issue.number }}" \
              --arg instructions "${{ github.event.comment.body }}" \
              '{repo: $repo, pr_number: $pr_number, instructions: $instructions}')"
